"""Render the sections of the quality reports.

Two reports are produced from the same per-faction stats:

- Per-addon `QUALITY_REPORT.md` — written into each addon directory.
  Self-contained: full glossary, this faction's snapshot, sub-guide
  detail table and input-data row. A maintainer testing a single guide
  reads only this file.
- Slim global `_quality_report.md` — written at the repo root.
  Snapshot of all factions plus a comparison table and global
  top/bottom sub-guide lists. Per-faction detail lives in the addons,
  not here, so the root file stays diff-friendly.

Each `render_*` function appends to a shared list of lines so callers
can compose reports without building intermediate strings. The
orchestrator (`writer.py`) decides which renderers run for which file.

The headline metric across this whole module is **rep / map unit**:
how much reputation a sub-guide delivers per unit of intra-zone walking
distance. There is no normalised 0-100 score — higher is better, with
no upper target. A change is an improvement if rep/dist goes up; the
absolute number is meaningful for trend tracking, not for comparison
between factions.
"""
from __future__ import annotations

from .aggregate import aggregate_pathing, sg_pathing_normal


# ---------- shared headers and glossary ----------


def render_global_header(lines: list[str], version: str, expansion: str) -> None:
    lines += [
        f'# Quality Report v{version} ({expansion.upper()})',
        '',
        'Auto-generated by `create.py --all`. Slim global summary across all',
        'factions. Per-faction detail (sub-guide tables, dropped quests,',
        'pathing breakdown) lives in each addon\'s `QUALITY_REPORT.md`.',
        '',
    ]


def render_addon_header(
    lines: list[str], faction_name: str, faction_id: int,
    version: str, expansion: str,
) -> None:
    lines += [
        f'# {faction_name} — Quality Report v{version} ({expansion.upper()})',
        '',
        f'Auto-generated by `create.py --faction {faction_name.lower()}`.',
        f'Pathing efficiency and quest coverage for ID {faction_id}.',
        '',
        'Useful as a baseline when tuning routing for this faction: tweak a',
        'constant or method, regenerate, diff this file.',
        '',
    ]


def render_glossary(lines: list[str]) -> None:
    """Glossary used inside per-addon reports. Kept here so each addon
    file is readable without cross-referencing a separate doc."""
    lines += [
        '## Glossary',
        '',
        '### Prefixes',
        '- **N-** = the normal section of a sub-guide (quests that stay inside the',
        '  zone). Feeds into the rep-per-distance metric.',
        '- **C-** = the complex section (cross-zone chains). Reported **for info',
        '  only** — it does NOT feed into rep-per-distance, because the long',
        '  cross-zone legs would distort the metric.',
        '',
        '### Pathing metrics (normal section)',
        '- **N-Dist**: sum of intra-zone euclidean map distance. Cross-zone hops',
        '  are flightpath/portal travel — not a meaningful running distance — so',
        '  they do not contribute to N-Dist.',
        '- **N-Jumps**: number of zone changes along the tour. For the normal',
        '  section this should be low; a non-zero value means a cross-zone',
        '  quest slipped through the complex extraction.',
        '- **N-Cluster**: number of cluster entries (groups of stops at the same',
        '  location, emitted together).',
        '- **N-Absorp** (absorption rate): fraction of stops sitting in clusters',
        '  with size >= 2. Diagnostic only — feeds nothing.',
        '- **N-Rep**: total rep from the normal-section quests. Fixed by the',
        '  input — does not move with routing changes.',
        '- **N-Rep/Dist**: rep per map-unit walked. **The headline quality',
        '  metric.** Higher is better, with no upper target. Track this when',
        '  comparing routing-method changes — if it went up, the new method',
        '  is better.',
        '',
    ]


# ---------- global slim report sections ----------


def render_global_snapshot(
    lines: list[str], grand: dict, totals: dict, total_subs: int,
    n_factions: int,
) -> None:
    """Headline KPIs across every faction in the bulk run."""
    abs_rate = (grand['n_clustered'] / grand['n_stops']) if grand['n_stops'] else 0.0
    rpd_global = (grand['n_rep'] / grand['n_dist']) if grand['n_dist'] > 0 else 0.0
    lines += [
        '## Snapshot',
        '',
        'Headline KPIs for diff comparisons. Routing changes should push',
        '**rep/dist up** and **distance down**; everything else is diagnostic.',
        '',
        f'- **Global Rep/Dist**: {rpd_global:.2f} rep / map unit '
        '— *the* quality metric, higher is better',
        f'- **Total Distance (Normal)**: {grand["n_dist"]:.0f} map units',
        f'- **Total Rep (Normal)**: {grand["n_rep"]} '
        '— input-fixed, does not move with routing changes',
        f'- **Total X-Jumps (Normal)**: {grand["n_jumps"]} (diagnostic)',
        f'- **Absorption Rate (Normal)**: {abs_rate:.1%} (diagnostic)',
        f'- **Lost Quests**: {totals["dropped"]} (of {totals["input"]})',
        f'- **Sub-Guides Total**: {total_subs} across {n_factions} factions',
        '',
        '### Complex section (info only, not part of the headline metric)',
        f'- distance: {grand["c_dist"]:.0f} | x-jumps: {grand["c_jumps"]} | rep: {grand["c_rep"]}',
        '',
    ]


def render_global_faction_comparison(lines: list[str], valid: list) -> None:
    """One row per faction with the columns that move with code changes.
    Static input counts are intentionally omitted — they live in each
    addon's per-addon report, where they are more useful in context.

    Sorted by **N-Rep/Dist** descending, so factions where routing has
    the most leverage sit at the top.
    """
    lines += [
        '## Faction Comparison',
        '',
        'Per-faction KPIs that respond to routing changes. Sorted by',
        '`N-Rep/Dist` (the headline metric). For sub-guide detail and',
        'dropped quests, see the addon-specific `QUALITY_REPORT.md`.',
        '',
        '| Faction | Sub-Guides | Lost | N-Dist | N-Jumps | N-Absorp | N-Rep | **N-Rep/Dist** |',
        '|---|---:|---:|---:|---:|---:|---:|---:|',
    ]

    rows: list[tuple[float, str]] = []
    for entry in valid:
        fname, _fid, _, _, stats = entry
        t = stats['totals']
        agg = aggregate_pathing(stats)
        lost_flag = f'**{t["dropped_no_zone"]}**' if t['dropped_no_zone'] else '0'
        rpd_value = (
            agg['normal_rep'] / agg['normal_distance']
            if agg['normal_distance'] > 0 else float('inf')
        )
        rep_per_dist = (
            f'**{rpd_value:.2f}**' if agg['normal_distance'] > 0 else '∞'
        )
        n_absorp = (
            agg['normal_clustered'] / agg['normal_stops']
            if agg['normal_stops'] else 0.0
        )
        n_subs = len(stats['sub_guides'])
        row = (
            f'| {fname} | {n_subs} | {lost_flag} | '
            f'{agg["normal_distance"]:.0f} | {agg["normal_jumps"]} | '
            f'{n_absorp:.0%} | {agg["normal_rep"]} | {rep_per_dist} |'
        )
        rows.append((rpd_value, row))

    rows.sort(key=lambda x: x[0], reverse=True)
    for _, row in rows:
        lines.append(row)
    lines.append('')


def render_global_top_bottom(lines: list[str], valid: list) -> None:
    """Top/bottom 20 sub-guides — the global optimization candidate list,
    ranked by rep/dist. Sub-guides with no walking distance (everything
    at one NPC) sit at the top with infinite rpd; they are listed last
    in the top group so they do not crowd out the genuinely tight tours.
    """
    all_sgs: list[tuple[str, str, dict, float]] = []
    for r in valid:
        for sg in r[4]['sub_guides']:
            if sg['normal_quests'] > 0:
                rpd = sg.get('rep_per_dist', 0.0)
                all_sgs.append((r[0], sg['name'], sg, rpd))
    # Push zero-distance entries to the bottom of the "top" list — they
    # are real perfection cases but not informative as the headline.
    all_sgs.sort(key=lambda x: (x[3] != float('inf'), x[3]), reverse=True)

    lines += [
        '## Top 20 Sub-Guides by Rep/Dist',
        '',
        '| Rank | Faction | Sub-Guide | **N-Rep/Dist** | N-Rep | N-Dist |',
        '|---:|---|---|---:|---:|---:|',
    ]
    for i, (fname, sname, sg, rpd) in enumerate(all_sgs[:20], 1):
        n_dist, _, _, _, n_rep = sg_pathing_normal(sg)
        rpd_label = f'**{rpd:.2f}**' if n_dist > 0 else '**∞**'
        lines.append(
            f'| {i} | {fname} | {sname} | {rpd_label} | '
            f'{n_rep} | {n_dist:.0f} |'
        )
    lines.append('')
    lines += [
        '## Bottom 20 Sub-Guides by Rep/Dist',
        '',
        'Optimisation candidates: rep is low *for the distance walked*. Note',
        'that 1-quest cleanup sub-guides naturally land here — there is',
        'nothing for routing to improve on a single fixed walk, so a low',
        'rep/dist there reflects the input, not a routing failure.',
        '',
        '| Rank | Faction | Sub-Guide | **N-Rep/Dist** | N-Rep | N-Dist | Quests |',
        '|---:|---|---|---:|---:|---:|---:|',
    ]
    for i, (fname, sname, sg, rpd) in enumerate(reversed(all_sgs[-20:]), 1):
        n_dist, _, _, _, n_rep = sg_pathing_normal(sg)
        rpd_label = f'**{rpd:.2f}**' if n_dist > 0 else '∞'
        lines.append(
            f'| {i} | {fname} | {sname} | {rpd_label} | '
            f'{n_rep} | {n_dist:.0f} | {sg["normal_quests"]} |'
        )
    lines.append('')


# ---------- per-addon report sections ----------


def render_addon_snapshot(
    lines: list[str], faction_name: str, stats: dict,
) -> None:
    """Snapshot for one faction. Mirrors the global snapshot's KPI list
    but scoped to this faction only — so a single-faction run produces a
    fully comparable file.
    """
    agg = aggregate_pathing(stats)
    abs_rate = (
        agg['normal_clustered'] / agg['normal_stops']
        if agg['normal_stops'] else 0.0
    )
    rpd = (
        agg['normal_rep'] / agg['normal_distance']
        if agg['normal_distance'] > 0 else 0.0
    )

    n_subs = len(stats['sub_guides'])
    t = stats['totals']

    lines += [
        '## Snapshot',
        '',
        f'- **Rep/Dist**: {rpd:.2f} rep / map unit '
        '— headline metric, higher is better',
        f'- **Distance (Normal)**: {agg["normal_distance"]:.0f} map units',
        f'- **Total Rep (Normal)**: {agg["normal_rep"]} (input-fixed)',
        f'- **X-Jumps (Normal)**: {agg["normal_jumps"]} (diagnostic)',
        f'- **Absorption Rate (Normal)**: {abs_rate:.1%} (diagnostic)',
        f'- **Sub-Guides**: {n_subs}',
    ]
    if t['dropped_no_zone']:
        lines.append(f'- **Lost Quests**: {t["dropped_no_zone"]}')
    if agg['complex_distance'] > 0 or agg['complex_rep'] > 0:
        lines += [
            '',
            '### Complex section (info only, not part of the headline metric)',
            f'- distance: {agg["complex_distance"]:.0f} | '
            f'x-jumps: {agg["complex_jumps"]} | rep: {agg["complex_rep"]}',
        ]
    lines.append('')


def render_addon_subguides(lines: list[str], stats: dict) -> None:
    """Per-sub-guide table for one faction. Sorted by **rep/dist**
    descending, so the densest sub-guides sit at the top and the
    optimisation candidates at the bottom. 1-quest sub-guides with
    fixed walk land low naturally — that reflects the input, not a
    routing failure.
    """
    lines += [
        '## Sub-Guides',
        '',
        '| Sub-Guide | **Rep/Dist** | Quests | N-Dist | N-Jumps | N-Cluster | N-Absorp | N-Rep |',
        '|---|---:|---:|---:|---:|---:|---:|---:|',
    ]
    sgs_sorted = sorted(
        stats['sub_guides'],
        key=lambda sg: (sg.get('rep_per_dist', 0.0), sg.get('normal_rep', 0)),
        reverse=True,
    )
    for sg in sgs_sorted:
        nq = sg['normal_quests']
        cq = sg['complex_quests']
        quests_label = f'{nq + cq}' if cq == 0 else f'{nq + cq} ({nq}+{cq})'
        n_dist, n_jumps, n_clusters, n_absorp, n_rep = sg_pathing_normal(sg)
        rpd = sg.get('rep_per_dist', 0.0)
        rpd_label = f'**{rpd:.2f}**' if n_dist > 0 else '**∞**'
        lines.append(
            f'| {sg["name"]} | {rpd_label} | {quests_label} | '
            f'{n_dist:.0f} | {n_jumps} | {n_clusters} | {n_absorp:.0%} | {n_rep} |'
        )
    lines.append('')


def render_addon_input(lines: list[str], stats: dict) -> None:
    """Quest counts and lost-quests detail for this faction."""
    t = stats['totals']
    agg = aggregate_pathing(stats)
    lines += [
        '## Input Data',
        '',
        f'- **Total quests**: {t["total_input"]} '
        f'({t["rep_quests"]} rep + {t["bridge_quests"]} bridge)',
        f'- **Kept**: {t["in_kept"]} '
        f'(routed into normal sub-guides, {agg["normal_rep"]} rep)',
        f'- **Complex**: {t["in_complex"]} '
        f'(cross-zone chains, {agg["complex_rep"]} rep)',
        f'- **In sub-guides**: {t["in_buckets"]}',
    ]
    if t['dropped_no_zone']:
        lines.append('')
        lines.append(
            f'### Lost ({t["dropped_no_zone"]})',
        )
        lines.append('')
        lines.append('Quests for which no zone could be determined (e.g.')
        lines.append('battleground zones missing from `ZONE_MAP`).')
        lines.append('')
        for qid, qname in t['dropped_quests']:
            lines.append(f'- Q{qid} `{qname}`')
        lines.append('')
    else:
        lines.append('')
