"""Render the sections of the quality reports.

Two reports are produced from the same per-faction stats:

- Per-addon `QUALITY_REPORT.md` — written into each addon directory.
  Self-contained: full glossary, this faction's snapshot, sub-guide
  detail table and input-data row. A maintainer testing a single guide
  reads only this file.
- Slim global `_quality_report.md` — written at the repo root.
  Snapshot of all factions plus a comparison table and global
  top/bottom sub-guide lists. Per-faction detail lives in the addons,
  not here, so the root file stays diff-friendly.

Each `render_*` function appends to a shared list of lines so callers
can compose reports without building intermediate strings. The
orchestrator (`writer.py`) decides which renderers run for which file.
"""
from __future__ import annotations

from .aggregate import aggregate_pathing, sg_pathing_normal


# ---------- shared headers and glossary ----------


def render_global_header(lines: list[str], version: str, expansion: str) -> None:
    lines += [
        f'# Quality Report v{version} ({expansion.upper()})',
        '',
        'Auto-generated by `create.py --all`. Slim global summary across all',
        'factions. Per-faction detail (sub-guide tables, dropped quests,',
        'pathing breakdown) lives in each addon\'s `QUALITY_REPORT.md`.',
        '',
    ]


def render_addon_header(
    lines: list[str], faction_name: str, faction_id: int,
    version: str, expansion: str,
) -> None:
    lines += [
        f'# {faction_name} — Quality Report v{version} ({expansion.upper()})',
        '',
        f'Auto-generated by `create.py --faction {faction_name.lower()}`.',
        f'Pathing efficiency and quest coverage for ID {faction_id}.',
        '',
        'Useful as a baseline when tuning routing for this faction: tweak a',
        'constant or method, regenerate, diff this file.',
        '',
    ]


def render_glossary(lines: list[str]) -> None:
    """Glossary used inside per-addon reports. Kept here so each addon
    file is readable without cross-referencing a separate doc."""
    lines += [
        '## Glossary',
        '',
        '### Prefixes',
        '- **N-** = the normal section of a sub-guide (quests that stay inside the',
        '  zone). Feeds into every efficiency metric.',
        '- **C-** = the complex section (cross-zone chains). Reported **for info',
        '  only** — it does NOT feed into the score or rep-per-distance, because',
        '  the long cross-zone legs would distort the metric.',
        '',
        '### Pathing metrics (normal section)',
        '- **N-Dist**: sum of intra-zone euclidean map distance. Cross-zone hops',
        '  are flightpath/portal travel — not a meaningful running distance — so',
        '  they do not contribute to N-Dist.',
        '- **N-Jumps**: number of zone changes along the tour. For the normal',
        '  section this should be low; a non-zero value means a cross-zone',
        '  quest slipped through the complex extraction.',
        '- **N-Cluster**: number of cluster entries (groups of stops at the same',
        '  location, emitted together).',
        '- **N-Absorp** (absorption rate): fraction of stops sitting in clusters',
        '  with size >= 2. High is good (cluster discovery groups stops well).',
        '- **N-Rep**: total rep from the normal-section quests.',
        '- **N-Rep/Dist**: rep per map-unit walked. Higher is better.',
        '',
        '### Efficiency score (0-100)',
        'A composite metric combining four pathing signals:',
        '- 50% rep / distance (logarithmic: rpd=10 -> 52p, 50 -> 85p, 100+ -> 100p)',
        '- 25% total rep (sqrt: 5000 -> 71p, 10000+ -> 100p) — rewards big sub-guides',
        '- 15% absorption rate (linear)',
        '- 10% cross-zone-jump penalty (0 jumps = 100p, 10+ = 0p)',
        '',
        'Visible in the sub-guide title as `(Eff. <score>, +<rep> rep)`.',
        '',
        '**Scale**: 80+ excellent, 60-79 solid, 40-59 mediocre, 20-39 weak, 0-19 poor.',
        '',
    ]


# ---------- global slim report sections ----------


def render_global_snapshot(
    lines: list[str], grand: dict, totals: dict, total_subs: int,
    global_avg_score: float, n_factions: int,
) -> None:
    """Headline KPIs across every faction in the bulk run."""
    abs_rate = (grand['n_clustered'] / grand['n_stops']) if grand['n_stops'] else 0.0
    rpd_global = (grand['n_rep'] / grand['n_dist']) if grand['n_dist'] > 0 else 0.0
    lines += [
        '## Snapshot',
        '',
        'Most important KPIs for diff comparisons. Routing/bucketing changes',
        'should improve these (score up, distance down, lost down).',
        '',
        f'- **Global ø Score**: {global_avg_score:.1f} / 100 — '
        f'rep-weighted average across all sub-guides',
        f'- **Global Efficiency**: {rpd_global:.2f} rep / map unit',
        f'- **Total Distance (Normal)**: {grand["n_dist"]:.0f} map units',
        f'- **Total X-Jumps (Normal)**: {grand["n_jumps"]}',
        f'- **Absorption Rate (Normal)**: {abs_rate:.1%}',
        f'- **Lost Quests**: {totals["dropped"]} (of {totals["input"]})',
        f'- **Sub-Guides Total**: {total_subs} across {n_factions} factions',
        '',
        '### Complex section (info only, not part of the efficiency)',
        f'- distance: {grand["c_dist"]:.0f} | x-jumps: {grand["c_jumps"]} | rep: {grand["c_rep"]}',
        '',
    ]


def render_global_faction_comparison(lines: list[str], valid: list) -> None:
    """One row per faction with the columns that move with code changes.
    Static input counts are intentionally omitted — they live in each
    addon's per-addon report, where they are more useful in context.
    """
    lines += [
        '## Faction Comparison',
        '',
        'Per-faction KPIs that respond to routing changes. For sub-guide',
        'detail and dropped quests, see the addon-specific',
        '`QUALITY_REPORT.md`.',
        '',
        '| Faction | Sub-Guides | Lost | N-Dist | N-Jumps | N-Absorp | N-Rep/Dist | ø Score |',
        '|---|---:|---:|---:|---:|---:|---:|---:|',
    ]
    for entry in valid:
        fname, _fid, _, _, stats = entry
        t = stats['totals']
        agg = aggregate_pathing(stats)
        lost_flag = f'**{t["dropped_no_zone"]}**' if t['dropped_no_zone'] else '0'
        rep_per_dist = (
            f'**{agg["normal_rep"] / agg["normal_distance"]:.1f}**'
            if agg['normal_distance'] > 0 else '∞'
        )
        scored = [(sg['efficiency_score'], sg.get('normal_rep', 0))
                  for sg in stats['sub_guides'] if sg['normal_quests'] > 0]
        if scored:
            sw = sum(w for _, w in scored)
            avg_score = (
                sum(s * w for s, w in scored) / sw if sw > 0
                else sum(s for s, _ in scored) / len(scored)
            )
            avg_label = f'**{avg_score:.0f}**'
        else:
            avg_label = '—'
        n_absorp = (agg['normal_clustered'] / agg['normal_stops']) if agg['normal_stops'] else 0.0
        n_subs = len(stats['sub_guides'])
        lines.append(
            f'| {fname} | {n_subs} | {lost_flag} | '
            f'{agg["normal_distance"]:.0f} | {agg["normal_jumps"]} | {n_absorp:.0%} | '
            f'{rep_per_dist} | {avg_label} |'
        )
    lines.append('')


def render_global_top_bottom(lines: list[str], valid: list) -> None:
    """Top/bottom 20 sub-guides — the global optimization candidate list."""
    all_sgs: list[tuple[str, str, dict]] = []
    for r in valid:
        for sg in r[4]['sub_guides']:
            if sg['normal_quests'] > 0:
                all_sgs.append((r[0], sg['name'], sg))
    all_sgs.sort(key=lambda x: x[2]['efficiency_score'], reverse=True)

    lines += [
        '## Top 20 Sub-Guides by Score',
        '',
        '| Rank | Faction | Sub-Guide | **Score** | N-Rep | N-Dist | N-Rep/Dist |',
        '|---:|---|---|---:|---:|---:|---:|',
    ]
    for i, (fname, sname, sg) in enumerate(all_sgs[:20], 1):
        n_dist, _, _, _, n_rep = sg_pathing_normal(sg)
        rpd = f'{n_rep / n_dist:.2f}' if n_dist > 0 else '∞'
        lines.append(
            f'| {i} | {fname} | {sname} | **{sg["efficiency_score"]}** | '
            f'{n_rep} | {n_dist:.0f} | {rpd} |'
        )
    lines.append('')
    lines += [
        '## Bottom 20 Sub-Guides by Score',
        '',
        'Optimisation candidates. Low score, lots of distance, or little rep.',
        '',
        '| Rank | Faction | Sub-Guide | **Score** | N-Rep | N-Dist | N-Rep/Dist |',
        '|---:|---|---|---:|---:|---:|---:|',
    ]
    for i, (fname, sname, sg) in enumerate(reversed(all_sgs[-20:]), 1):
        n_dist, _, _, _, n_rep = sg_pathing_normal(sg)
        rpd = f'{n_rep / n_dist:.2f}' if n_dist > 0 else '∞'
        lines.append(
            f'| {i} | {fname} | {sname} | **{sg["efficiency_score"]}** | '
            f'{n_rep} | {n_dist:.0f} | {rpd} |'
        )
    lines.append('')


# ---------- per-addon report sections ----------


def render_addon_snapshot(
    lines: list[str], faction_name: str, stats: dict,
) -> None:
    """Snapshot for one faction. Mirrors the global snapshot's KPI list
    but scoped to this faction only — so a single-faction run produces a
    fully comparable file.
    """
    agg = aggregate_pathing(stats)
    abs_rate = (agg['normal_clustered'] / agg['normal_stops']) if agg['normal_stops'] else 0.0
    rpd = (agg['normal_rep'] / agg['normal_distance']) if agg['normal_distance'] > 0 else 0.0

    scored = [(sg['efficiency_score'], sg.get('normal_rep', 0))
              for sg in stats['sub_guides'] if sg['normal_quests'] > 0]
    if scored:
        sw = sum(w for _, w in scored)
        avg = sum(s * w for s, w in scored) / sw if sw > 0 else sum(
            s for s, _ in scored
        ) / len(scored)
    else:
        avg = 0.0

    n_subs = len(stats['sub_guides'])
    t = stats['totals']

    lines += [
        '## Snapshot',
        '',
        f'- **ø Score**: {avg:.1f} / 100',
        f'- **Efficiency**: {rpd:.2f} rep / map unit',
        f'- **Distance (Normal)**: {agg["normal_distance"]:.0f} map units',
        f'- **X-Jumps (Normal)**: {agg["normal_jumps"]}',
        f'- **Absorption Rate (Normal)**: {abs_rate:.1%}',
        f'- **Total Rep (Normal)**: {agg["normal_rep"]}',
        f'- **Sub-Guides**: {n_subs}',
    ]
    if t['dropped_no_zone']:
        lines.append(f'- **Lost Quests**: {t["dropped_no_zone"]}')
    if agg['complex_distance'] > 0 or agg['complex_rep'] > 0:
        lines += [
            '',
            '### Complex section (info only, not part of the efficiency)',
            f'- distance: {agg["complex_distance"]:.0f} | '
            f'x-jumps: {agg["complex_jumps"]} | rep: {agg["complex_rep"]}',
        ]
    lines.append('')


def render_addon_subguides(lines: list[str], stats: dict) -> None:
    """Per-sub-guide table for one faction. Sorted by score so the best
    work is at the top and optimisation candidates sit at the bottom."""
    lines += [
        '## Sub-Guides',
        '',
        '| Sub-Guide | Score | Quests | N-Dist | N-Jumps | N-Cluster | N-Absorp | N-Rep/Dist |',
        '|---|---:|---:|---:|---:|---:|---:|---:|',
    ]
    sgs_sorted = sorted(
        stats['sub_guides'],
        key=lambda sg: (sg['efficiency_score'], sg.get('normal_rep', 0)),
        reverse=True,
    )
    for sg in sgs_sorted:
        nq = sg['normal_quests']
        cq = sg['complex_quests']
        quests_label = f'{nq + cq}' if cq == 0 else f'{nq + cq} ({nq}+{cq})'
        n_dist, n_jumps, n_clusters, n_absorp, n_rep = sg_pathing_normal(sg)
        rep_per = f'{n_rep / n_dist:.2f}' if n_dist > 0 else '∞'
        score = sg['efficiency_score']
        lines.append(
            f'| {sg["name"]} | **{score}** | {quests_label} | '
            f'{n_dist:.0f} | {n_jumps} | {n_clusters} | {n_absorp:.0%} | {rep_per} |'
        )
    lines.append('')


def render_addon_input(lines: list[str], stats: dict) -> None:
    """Quest counts and lost-quests detail for this faction."""
    t = stats['totals']
    agg = aggregate_pathing(stats)
    lines += [
        '## Input Data',
        '',
        f'- **Total quests**: {t["total_input"]} '
        f'({t["rep_quests"]} rep + {t["bridge_quests"]} bridge)',
        f'- **Kept**: {t["in_kept"]} '
        f'(routed into normal sub-guides, {agg["normal_rep"]} rep)',
        f'- **Complex**: {t["in_complex"]} '
        f'(cross-zone chains, {agg["complex_rep"]} rep)',
        f'- **In sub-guides**: {t["in_buckets"]}',
    ]
    if t['dropped_no_zone']:
        lines.append('')
        lines.append(
            f'### Lost ({t["dropped_no_zone"]})',
        )
        lines.append('')
        lines.append('Quests for which no zone could be determined (e.g.')
        lines.append('battleground zones missing from `ZONE_MAP`).')
        lines.append('')
        for qid, qname in t['dropped_quests']:
            lines.append(f'- Q{qid} `{qname}`')
        lines.append('')
    else:
        lines.append('')
