"""Render the seven sections of the quality report into Markdown lines.

Each `render_*` function appends to a shared list of lines and returns it.
Order matters — section 1 (snapshot) comes before section 2 (faction
comparison), etc. The orchestrator (`writer.write_quality_report`) calls
them in order with the pre-aggregated stats they need.
"""
from __future__ import annotations

from .aggregate import aggregate_pathing, sg_pathing_normal


def render_header(lines: list[str], version: str, expansion: str) -> None:
    lines += [
        f'# Quality Report v{version} ({expansion.upper()})',
        '',
        'Auto-generated by `create.py --all`. A snapshot of quest coverage and',
        'pathing efficiency for every faction. Useful as a baseline: tweak a',
        'constant or heuristic, regenerate, diff the new report.',
        '',
    ]


def render_glossary(lines: list[str]) -> None:
    lines += [
        '## Glossary',
        '',
        '### Prefixes',
        '- **N-** = the normal section of a sub-guide (quests that stay inside the',
        '  zone). Feeds into every efficiency metric.',
        '- **C-** = the complex section (cross-zone chains). Reported **for info',
        '  only** — it does NOT feed into the score or rep-per-distance, because',
        '  the long cross-zone legs would distort the metric.',
        '',
        '### Quest counts',
        '- **Total**: quests pulled from the Questie DB that are either rep or',
        '  bridge quests for this faction (input).',
        '- **Rep**: quests that grant rep directly.',
        '- **Bridge**: prerequisite quests with no rep reward, kept so the chain',
        '  is acceptable in-game.',
        '- **Kept**: quests emitted into normal sub-guides.',
        '- **Complex**: cross-zone quests routed into the complex section.',
        '- **Buckets**: quests that actually ended up in some sub-guide.',
        '- **Lost**: quests for which no zone could be determined (e.g.',
        '  battleground zones missing from `ZONE_MAP`). They are dropped.',
        '',
        '### Pathing metrics (normal section)',
        '- **N-Dist**: sum of intra-zone euclidean map distance. Cross-zone hops',
        '  are flightpath/portal travel — not a meaningful running distance — so',
        '  they do not contribute to N-Dist.',
        '- **N-Jumps**: number of zone changes along the tour. For the normal',
        '  section this should be low; a non-zero value means a cross-zone',
        '  quest slipped through the complex extraction.',
        '- **N-Cluster**: number of cluster entries (groups of stops at the same',
        '  location, emitted together).',
        '- **N-Absorp** (absorption rate): fraction of stops sitting in clusters',
        '  with size >= 2. High is good (cluster discovery groups stops well).',
        '- **N-Rep**: total rep from the normal-section quests.',
        '- **N-Rep/Dist**: rep per map-unit walked. Higher is better.',
        '',
        '### Complex info',
        '- **C-Dist / C-Jumps / C-Rep**: same meaning as the N-* fields but for',
        '  the complex section. Reported for context only.',
        '',
        '### Efficiency score (0-100)',
        'A composite metric combining four pathing signals:',
        '- 50% rep / distance (logarithmic: rpd=10 -> 52p, 50 -> 85p, 100+ -> 100p)',
        '- 25% total rep (sqrt: 5000 -> 71p, 10000+ -> 100p) — rewards big sub-guides',
        '- 15% absorption rate (linear)',
        '- 10% cross-zone-jump penalty (0 jumps = 100p, 10+ = 0p)',
        '',
        'Visible in the sub-guide title as `(Eff. <score>, +<rep> rep)`.',
        '',
        '**Scale**: 80+ excellent, 60-79 solid, 40-59 mediocre, 20-39 weak, 0-19 poor.',
        '',
        '### ø Score (faction average)',
        'Weighted average of all sub-guide scores in a faction, weighted by',
        'normal rep so small no-rep sub-guides do not pull the average down.',
        '',
    ]


def render_snapshot(
    lines: list[str], grand: dict, totals: dict, total_subs: int, global_avg_score: float,
) -> None:
    abs_rate = (grand['n_clustered'] / grand['n_stops']) if grand['n_stops'] else 0.0
    rpd_global = (grand['n_rep'] / grand['n_dist']) if grand['n_dist'] > 0 else 0.0
    lines += [
        '## 1. Snapshot Headline',
        '',
        'The most important KPIs for diff comparisons. Routing/bucketing changes',
        'should improve these (score up, distance down, lost down).',
        '',
        f'- **Global ø Score**: {global_avg_score:.1f} / 100',
        f'- **Global Efficiency**: {rpd_global:.2f} rep / map unit',
        f'- **Total Distance (Normal)**: {grand["n_dist"]:.0f} map units',
        f'- **Total X-Jumps (Normal)**: {grand["n_jumps"]}',
        f'- **Absorption Rate (Normal)**: {abs_rate:.1%}',
        f'- **Lost Quests**: {totals["dropped"]} (of {totals["input"]})',
        f'- **Sub-Guides Total**: {total_subs}',
        '',
        '### Complex section (info only, not part of the efficiency)',
        f'- distance: {grand["c_dist"]:.0f} | x-jumps: {grand["c_jumps"]} | rep: {grand["c_rep"]}',
        '',
    ]


def render_faction_comparison(lines: list[str], valid: list) -> None:
    lines += [
        '## 2. Faction Comparison (diff-relevant)',
        '',
        'Limited to columns that move with code changes. Static quest counts',
        '(Total/Rep/Bridge/Kept/Complex) are in section 7.',
        '',
        '| Faction | Buckets | Lost | N-Dist | N-Jumps | N-Absorp | N-Rep/Dist | ø Score |',
        '|---|---:|---:|---:|---:|---:|---:|---:|',
    ]
    for entry in valid:
        fname, fid, _, _, stats = entry
        t = stats['totals']
        agg = aggregate_pathing(stats)
        lost_flag = f'**{t["dropped_no_zone"]}**' if t['dropped_no_zone'] else '0'
        rep_per_dist = (
            f'**{agg["normal_rep"] / agg["normal_distance"]:.1f}**'
            if agg['normal_distance'] > 0 else '∞'
        )
        scored = [(sg['efficiency_score'], sg.get('normal_rep', 0))
                  for sg in stats['sub_guides'] if sg['normal_quests'] > 0]
        if scored:
            sw = sum(w for _, w in scored)
            avg_score = (
                sum(s * w for s, w in scored) / sw if sw > 0
                else sum(s for s, _ in scored) / len(scored)
            )
            avg_label = f'**{avg_score:.0f}**'
        else:
            avg_label = '—'
        n_absorp = (agg['normal_clustered'] / agg['normal_stops']) if agg['normal_stops'] else 0.0
        lines.append(
            f'| {fname} | {t["in_buckets"]} | {lost_flag} | '
            f'{agg["normal_distance"]:.0f} | {agg["normal_jumps"]} | {n_absorp:.0%} | '
            f'{rep_per_dist} | {avg_label} |'
        )
    lines.append('')


def render_per_faction_detail(lines: list[str], valid: list) -> None:
    lines += [
        '## 3. Per-Faction Detail',
        '',
        'Each faction with its sub-guides sorted by score.',
        '',
    ]
    for entry in valid:
        fname, fid, _, _, stats = entry
        t = stats['totals']
        agg = aggregate_pathing(stats)
        lines.append(f'### {fname} (ID {fid})')
        lines.append('')
        rep_per_dist = (
            f'{agg["normal_rep"] / agg["normal_distance"]:.2f}'
            if agg['normal_distance'] > 0 else '∞'
        )
        n_absorp = (agg['normal_clustered'] / agg['normal_stops']) if agg['normal_stops'] else 0.0
        lines.append(
            f'**Normal**: {agg["normal_distance"]:.0f} dist | {agg["normal_jumps"]} jumps | '
            f'{n_absorp:.1%} absorp | {agg["normal_rep"]} rep | **{rep_per_dist}** rep/dist'
        )
        if agg['complex_distance'] > 0 or agg['complex_rep'] > 0:
            lines.append(
                f'**Complex** (info): {agg["complex_distance"]:.0f} dist | '
                f'{agg["complex_jumps"]} jumps | {agg["complex_rep"]} rep'
            )
        if t['dropped_no_zone']:
            lines.append(f'**Lost**: {t["dropped_no_zone"]} quests:')
            for qid, qname in t['dropped_quests']:
                lines.append(f'  - Q{qid} `{qname}`')
        lines.append('')
        lines.append(
            '| Sub-Guide | Score | Quests | N-Dist | N-Jumps | N-Cluster | N-Absorp | N-Rep/Dist |'
        )
        lines.append('|---|---:|---:|---:|---:|---:|---:|---:|')
        sgs_sorted = sorted(
            stats['sub_guides'],
            key=lambda sg: (sg['efficiency_score'], sg.get('normal_rep', 0)),
            reverse=True,
        )
        for sg in sgs_sorted:
            nq = sg['normal_quests']
            cq = sg['complex_quests']
            quests_label = f'{nq + cq}' if cq == 0 else f'{nq + cq} ({nq}+{cq})'
            n_dist, n_jumps, n_clusters, n_absorp, n_rep = sg_pathing_normal(sg)
            rep_per = f'{n_rep / n_dist:.2f}' if n_dist > 0 else '∞'
            score = sg['efficiency_score']
            lines.append(
                f'| {sg["name"]} | **{score}** | {quests_label} | '
                f'{n_dist:.0f} | {n_jumps} | {n_clusters} | {n_absorp:.0%} | {rep_per} |'
            )
        lines.append('')


def render_faction_ranking(lines: list[str], valid: list) -> None:
    factions_with_rep = [
        (r[0], aggregate_pathing(r[4])) for r in valid
        if aggregate_pathing(r[4])['normal_distance'] > 0
    ]
    factions_with_rep.sort(
        key=lambda x: x[1]['normal_rep'] / x[1]['normal_distance'], reverse=True,
    )
    lines += [
        '## 4. Faction Ranking by Efficiency (N-Rep / N-Dist)',
        '',
        '| Rank | Faction | N-Rep | N-Dist | **N-Rep/Dist** |',
        '|---:|---|---:|---:|---:|',
    ]
    for i, (fname, agg) in enumerate(factions_with_rep, 1):
        rpd = agg['normal_rep'] / agg['normal_distance']
        lines.append(f'| {i} | {fname} | {agg["normal_rep"]} | {agg["normal_distance"]:.0f} | **{rpd:.2f}** |')
    lines.append('')


def render_top_bottom_subguides(lines: list[str], valid: list) -> None:
    all_sgs: list[tuple[str, str, dict]] = []
    for r in valid:
        for sg in r[4]['sub_guides']:
            if sg['normal_quests'] > 0:
                all_sgs.append((r[0], sg['name'], sg))
    all_sgs.sort(key=lambda x: x[2]['efficiency_score'], reverse=True)

    lines += [
        '## 5. Top 20 Sub-Guides by Score',
        '',
        '| Rank | Faction | Sub-Guide | **Score** | N-Rep | N-Dist | N-Rep/Dist |',
        '|---:|---|---|---:|---:|---:|---:|',
    ]
    for i, (fname, sname, sg) in enumerate(all_sgs[:20], 1):
        n_dist, _, _, _, n_rep = sg_pathing_normal(sg)
        rpd = f'{n_rep / n_dist:.2f}' if n_dist > 0 else '∞'
        lines.append(
            f'| {i} | {fname} | {sname} | **{sg["efficiency_score"]}** | '
            f'{n_rep} | {n_dist:.0f} | {rpd} |'
        )
    lines.append('')
    lines += [
        '## 6. Bottom 20 Sub-Guides by Score',
        '',
        'Optimisation candidates. Low score, lots of distance, or little rep.',
        '',
        '| Rank | Faction | Sub-Guide | **Score** | N-Rep | N-Dist | N-Rep/Dist |',
        '|---:|---|---|---:|---:|---:|---:|',
    ]
    for i, (fname, sname, sg) in enumerate(reversed(all_sgs[-20:]), 1):
        n_dist, _, _, _, n_rep = sg_pathing_normal(sg)
        rpd = f'{n_rep / n_dist:.2f}' if n_dist > 0 else '∞'
        lines.append(
            f'| {i} | {fname} | {sname} | **{sg["efficiency_score"]}** | '
            f'{n_rep} | {n_dist:.0f} | {rpd} |'
        )
    lines.append('')


def render_input_data(lines: list[str], valid: list, totals: dict, grand: dict) -> None:
    lines += [
        '## 7. Input Data (static, reality-check)',
        '',
        'Quest counts per faction. These only change when the filter logic or',
        'the Questie DB changes — not relevant for routing diffs.',
        '',
        '| Faction | Total | Rep | Bridge | Kept | Complex | N-Rep | C-Rep |',
        '|---|---:|---:|---:|---:|---:|---:|---:|',
    ]
    for entry in valid:
        fname, _, _, _, stats = entry
        t = stats['totals']
        agg = aggregate_pathing(stats)
        lines.append(
            f'| {fname} | {t["total_input"]} | {t["rep_quests"]} | {t["bridge_quests"]} | '
            f'{t["in_kept"]} | {t["in_complex"]} | {agg["normal_rep"]} | {agg["complex_rep"]} |'
        )
    lines += [
        '',
        f'**Aggregate**: {totals["input"]} total | {totals["kept"]} kept | {totals["complex"]} complex | '
        f'{grand["n_rep"]} N-Rep | {grand["c_rep"]} C-Rep',
        '',
    ]
