"""Static reference data — split by domain across submodules.

Importing from `guides_generator.constants` re-exports every name so callers
do not have to know which submodule a constant lives in.
"""
from .databases import DB_FILES, INTERFACE_VERSION, QUESTIE_RAW
from .dungeons import DUNGEON_BOSS_NPCS, DUNGEON_ENTRANCES
from .factions import (
    ALLIANCE_FACTIONS, FACTION_GROUPS, FACTION_NAMES, HORDE_FACTIONS,
)
from .paths import (
    ADDONS_DIR, AUTHOR, CACHE_DIR, CHANGELOG_DIR, DEFAULT_EXPANSION_FOR_ALL,
    FALLBACK_VERSION, LICENSE_PATH, REPO_URL,
)
from .races_classes import (
    ALL_CLASSES_MASK, ALL_RACES_MASK, ALLIANCE_MASK, CLASS_FLAGS, HORDE_MASK,
    RACE_FLAGS, RACES_ALLIANCE, RACES_HORDE,
)
from .zones import (
    CITY_ZONES, DEFAULT_CLUSTER_RADIUS, LOC_TOL, TIER_FIT_TOLERANCE, ZONE_CLUSTER_RADIUS,
    ZONE_LEVEL_TIER, ZONE_MAP,
)

__all__ = [
    'ADDONS_DIR', 'ALLIANCE_FACTIONS', 'ALLIANCE_MASK', 'ALL_CLASSES_MASK',
    'ALL_RACES_MASK', 'AUTHOR', 'CACHE_DIR', 'CHANGELOG_DIR', 'CITY_ZONES',
    'CLASS_FLAGS', 'DB_FILES', 'DEFAULT_CLUSTER_RADIUS',
    'DEFAULT_EXPANSION_FOR_ALL', 'DUNGEON_BOSS_NPCS', 'DUNGEON_ENTRANCES',
    'FACTION_GROUPS', 'FACTION_NAMES', 'FALLBACK_VERSION', 'HORDE_FACTIONS',
    'HORDE_MASK', 'INTERFACE_VERSION', 'LICENSE_PATH', 'LOC_TOL', 'QUESTIE_RAW',
    'RACE_FLAGS',
    'RACES_ALLIANCE', 'RACES_HORDE', 'REPO_URL', 'TIER_FIT_TOLERANCE',
    'ZONE_CLUSTER_RADIUS', 'ZONE_LEVEL_TIER', 'ZONE_MAP',
]
